# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import inference_pb2 as inference__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in inference_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class InferenceServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ChatCompletion = channel.unary_stream(
                '/tactorder.inference.InferenceService/ChatCompletion',
                request_serializer=inference__pb2.ChatRequest.SerializeToString,
                response_deserializer=inference__pb2.ChatResponse.FromString,
                _registered_method=True)
        self.Embeddings = channel.unary_unary(
                '/tactorder.inference.InferenceService/Embeddings',
                request_serializer=inference__pb2.EmbeddingRequest.SerializeToString,
                response_deserializer=inference__pb2.EmbeddingResponse.FromString,
                _registered_method=True)
        self.ListModels = channel.unary_unary(
                '/tactorder.inference.InferenceService/ListModels',
                request_serializer=inference__pb2.ListModelsRequest.SerializeToString,
                response_deserializer=inference__pb2.ListModelsResponse.FromString,
                _registered_method=True)


class InferenceServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ChatCompletion(self, request, context):
        """Chat completion with streaming support
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Embeddings(self, request, context):
        """Embedding generation
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListModels(self, request, context):
        """Model discovery
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InferenceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ChatCompletion': grpc.unary_stream_rpc_method_handler(
                    servicer.ChatCompletion,
                    request_deserializer=inference__pb2.ChatRequest.FromString,
                    response_serializer=inference__pb2.ChatResponse.SerializeToString,
            ),
            'Embeddings': grpc.unary_unary_rpc_method_handler(
                    servicer.Embeddings,
                    request_deserializer=inference__pb2.EmbeddingRequest.FromString,
                    response_serializer=inference__pb2.EmbeddingResponse.SerializeToString,
            ),
            'ListModels': grpc.unary_unary_rpc_method_handler(
                    servicer.ListModels,
                    request_deserializer=inference__pb2.ListModelsRequest.FromString,
                    response_serializer=inference__pb2.ListModelsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tactorder.inference.InferenceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('tactorder.inference.InferenceService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class InferenceService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ChatCompletion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/tactorder.inference.InferenceService/ChatCompletion',
            inference__pb2.ChatRequest.SerializeToString,
            inference__pb2.ChatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Embeddings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tactorder.inference.InferenceService/Embeddings',
            inference__pb2.EmbeddingRequest.SerializeToString,
            inference__pb2.EmbeddingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListModels(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tactorder.inference.InferenceService/ListModels',
            inference__pb2.ListModelsRequest.SerializeToString,
            inference__pb2.ListModelsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
